#!/bin/bash
# scripts/smoke-test-ex14.sh
# Verifies provisioning and teardown of BQ and Dataplex resources in the vibe-cabral project context.

set -euo pipefail

PROJECT_ID="vibe-cabral"
LOCATION="us-central1"
DATASET_ID="raw_data_lake"
TABLE_ID="customer_feedback_raw"
ASPECT_TYPE_ID="ai-steward-metadata"

echo "=== STARTING SMOKE TEST FOR EXERCISE 14 ==="
echo "Target Project: ${PROJECT_ID}"
echo "Location: ${LOCATION}"

# 1. Set gcloud project
echo -e "\n1. Ensuring gcloud is set to project context: ${PROJECT_ID}..."
gcloud config set project "${PROJECT_ID}"

# 2. Enable Services
echo -e "\n2. Verifying services are enabled..."
gcloud services enable \
    bigquery.googleapis.com \
    dataplex.googleapis.com \
    aiplatform.googleapis.com

# 3. Create BigQuery Dataset
echo -e "\n3. Creating BigQuery Dataset: ${DATASET_ID}..."
if bq --location="${LOCATION}" show --dataset "${PROJECT_ID}:${DATASET_ID}" >/dev/null 2>&1; then
    echo "Dataset already exists, skipping creation."
else
    bq --location="${LOCATION}" mk -d "${DATASET_ID}"
    echo "BigQuery Dataset created successfully."
fi

# 4. Create BigQuery Table & Insert Mock Records
echo -e "\n4. Provisioning table ${TABLE_ID} and seeding mock logs..."
bq query --use_legacy_sql=false "
  CREATE OR REPLACE TABLE ${DATASET_ID}.${TABLE_ID} (
    entry_id STRING,
    created_at TIMESTAMP,
    cust_val FLOAT64,
    usr_fb_txt STRING
  );
  
  INSERT INTO ${DATASET_ID}.${TABLE_ID} (entry_id, created_at, cust_val, usr_fb_txt)
  VALUES
    ('101', CURRENT_TIMESTAMP(), 850.50, 'Loved the new UI! But support was slow. Contact me at carl@example.com.'),
    ('102', CURRENT_TIMESTAMP(), 120.00, 'Product broke after 2 days. Terrible service, do not recommend!'),
    ('103', CURRENT_TIMESTAMP(), 4500.00, 'Excellent enterprise support, very happy with the transition.');
"
echo "BigQuery Table initialized and mock records inserted successfully."

# 5. Create Aspect Type Schema in official MetadataTemplate format
echo -e "\n5. Creating aspect type schema JSON..."
cat << 'EOF' > aspect_schema.json
{
  "name": "ai_steward_metadata",
  "type": "record",
  "recordFields": [
    {
      "name": "sentiment_summary",
      "type": "string",
      "index": 1,
      "annotations": {
        "displayName": "Customer Sentiment",
        "description": "Customer Sentiment Summary"
      }
    },
    {
      "name": "contains_pii",
      "type": "bool",
      "index": 2,
      "annotations": {
        "displayName": "Contains PII Data",
        "description": "Whether the table contains unmasked PII data"
      }
    },
    {
      "name": "steward_notes",
      "type": "string",
      "index": 3,
      "annotations": {
        "displayName": "AI Steward Curation Notes",
        "description": "Descriptive curation notes generated by AI"
      }
    }
  ]
}
EOF
echo "aspect_schema.json created."

# 6. Create Dataplex Aspect Type
echo -e "\n6. Creating Dataplex Aspect Type: ${ASPECT_TYPE_ID}..."
# Delete if already exists to ensure clean smoke test
if gcloud dataplex aspect-types describe "${ASPECT_TYPE_ID}" --location="${LOCATION}" >/dev/null 2>&1; then
    echo "Warning: Aspect Type ${ASPECT_TYPE_ID} already exists. Re-creating..."
    gcloud dataplex aspect-types delete "${ASPECT_TYPE_ID}" --location="${LOCATION}" --quiet
fi

gcloud dataplex aspect-types create "${ASPECT_TYPE_ID}" \
    --location="${LOCATION}" \
    --display-name="AI Curation Steward Aspect" \
    --description="Metadata generated automatically by the Antigravity Autonomous Data Steward agent." \
    --metadata-template-file-name="aspect_schema.json"

echo "Dataplex Aspect Type created successfully."

# 7. Verify Descriptions
echo -e "\n7. Running verification descriptions..."
gcloud dataplex aspect-types describe "${ASPECT_TYPE_ID}" --location="${LOCATION}"
bq show "${PROJECT_ID}:${DATASET_ID}.${TABLE_ID}"

# =====================================================================
# Teardown / Clean up
# =====================================================================
echo -e "\n=== TEARDOWN: Cleaning up smoke test resources ==="

echo "8. Deleting Dataplex Aspect Type..."
gcloud dataplex aspect-types delete "${ASPECT_TYPE_ID}" --location="${LOCATION}" --quiet
echo "Aspect Type deleted."

echo "9. Force deleting BigQuery dataset..."
bq rm -r -f -d "${DATASET_ID}"
echo "BigQuery dataset deleted."

# Clean up local file
rm -f aspect_schema.json

echo -e "\n=== SMOKE TEST COMPLETED SUCCESSFULLY! ==="
